### ISSUE TITLE
Support additional data with the Flow 'query' parameter

### ISSUE THREAD

**Issue by showes** [showes/NgFlowSample#4]
Created because of a comment in issue #2 

Flow allows additional data to be passed via a query object or funciton: 
```
var flow = new Flow({
  target:'/api/photo/redeem-upload-token', 
  query:{upload_token:'my_token'}
});
```

From the docs: 
query: Extra parameters to include in the multipart POST with data. This can be an object or a function. If a function, it will be passed a FlowFile, a FlowChunk object and a isTest boolean (Default: {})

**Comment by showes** [comment]
@jonjalberghini Does commit 392e8bd give you everything you need? Is there anything different I can do for it?

**Comment by jonjalberghini** [comment]
Thanks so much for your help. I was getting an error on upload once in a while from 
 if (fileMeta.IsComplete)
{
// Since we are using a cache and memory is automatically disposed,
// we don't need to do this, so we won't so we can keep a record of
// our completed uploads.
//uploadChunkCache.Remove(chunkMeta.FlowIdentifier);
}

This code you removed. Because after the last chunk was uploaded the Metadata was deleted and then the HasRecievedChunk couldn't find it. Shouldn't be an issue anymore with the memory cache.
And funny enough it only happened once in a while. Do you think that was the cause of the error?

As I am testing more it seems that 
		public void RegisterChunkAsReceived(FlowMetaData flowMeta)
		{
			ChunkArray[ChunkIndex(flowMeta.FlowChunkNumber)] = true;
			TotalChunksReceived++;
		}
should be 
		public void RegisterChunkAsReceived(FlowMetaData flowMeta)
		{
                        if (ChunkArray[ChunkIndex(flowMeta.FlowChunkNumber)] != true){
			        ChunkArray[ChunkIndex(flowMeta.FlowChunkNumber)] = true;
			        TotalChunksReceived++;
                         }
		}

If a chunk is resent will it not throw off the TotalChunksReceived?

**Comment by jonjalberghini** [comment]
Was this supposed to be commented out?
`
       // Strict properties: you have to specify each property in the constructor and handle it yourself
       var strictMetaData = new FlowMetaData(flowMetaDictionary);
`

**Comment by showes** [comment]
No, I left it in there as an example of an alternative coding style. It can be safely commented out though.

**Comment by jonjalberghini** [comment]
The code in FlowUploadProcessor is 
`		private static FileMetaData GetFileMetaData(string flowIdentifier)
		{
			lock (chunkCacheLock)
			{
				return uploadChunkCache[flowIdentifier] as FileMetaData;
			}
		}
`
and should be 
`
               private static FileMetaData GetFileMetaData(string flowIdentifier)
		{
			lock (chunkCacheLock)
			{
				return new FileMetaData(uploadChunkCache[flowIdentifier] as FlowMetaData);
			}
		}
`
Am I correct?

**Comment by showes** [comment]
Ah I see your point. This is what I get for doing things at 2 in the morning and not properly testing them. My apologies!

**Comment by samhowes** [comment]
d6c2e16 is what I meant to do.

**Comment by agostnello** [comment]
I changed this function to this, if for some reason a packet is resubmitted the TotalChunksReceived becomes out of sync.

`public void RegisterChunkAsReceived(FlowMetaData flowMeta)
        {
            if (ChunkArray[ChunkIndex(flowMeta.FlowChunkNumber)] != true)
            {
                ChunkArray[ChunkIndex(flowMeta.FlowChunkNumber)] = true;
                TotalChunksReceived++;
            }
        }
`

**Comment by agostnello** [comment]
Thanks so much for all the help!!
